# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ident', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Bundesland')),
            ],
        ),
    ]
