# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundesland',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mindestmass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Bundesland')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.Fish')),
            ],
        ),
        migrations.CreateModel(
            name='Schonzeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('bundesland', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.Bundesland')),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.Fish')),
            ],
        ),
    ]
