# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('water', '0001_initial'),
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fish.Fish')),
            ],
        ),
        migrations.CreateModel(
            name='FisherMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='catch',
            name='fisherman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fisherman.FisherMan'),
        ),
        migrations.AddField(
            model_name='catch',
            name='water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.Water'),
        ),
    ]
